### ISSUE TITLE
feature: Create and Publish a PyPi package

### ISSUE THREAD

**Issue by Apoorve73** [skamranahmed/indian-stocks-cli#1]
# Overview
The project seems really fascinating and I believe a PyPi package can be published for the same. 
Please let me know your thoughts @skamranahmed and I can start working on it if it's a Yes.

**Comment by skamranahmed** [comment]
Hi @Apoorve73 bro, I wasn't active. Saw your comment a bit late. Although I already started working on the PyPi package back in October, you can contribute to it if you feel. I have just released the first verision.

https://pypi.org/project/ind-ticker/
